### PR TITLE
Standardize id attribute

### PR DESCRIPTION
**Pull request by yuripourre**
Reference: https://docs.mongodb.org/manual/reference/object-id/

### CODE REVIEW

**Comment by bihe** [comment]
Makes sense!

**Comment by bihe** [comment]
Release of new maven module will follow, THX.

**Comment by yuripourre** [comment]
Ops, I guess the `@Id` annotation already does it.

[https://github.com/mongodb/morphia/wiki/AllAnnotations#id](https://github.com/mongodb/morphia/wiki/AllAnnotations#id)

Sorry about the mess.

**Comment by bihe** [comment]
No problem - did not read the doc either. This way it is more expressive.

**Pull request merged**
